### ISSUE TITLE
Add SEO descriptions as well

### ISSUE THREAD

**Issue by nielsenramon** [screeninteraction/jekyll-multiple-languages-plugin#46]
It would be nice to have seo descriptions translated as well together with titles. 
So we can use something like:

```liquid
<title>{% t page.title %}</title>
<meta name="description" content="{% t page.description %}">
```

**Comment by kurtsson** [comment]
If you put the SEO descriptions in the language files, I can't see why this shouldn't work already.

**Comment by nielsenramon** [comment]
@kurtsson This issue can be closed. It was not working because of a baseurl bug :)
