### ISSUE TITLE
Does this plugin work with gh-pages's generator?

### ISSUE THREAD

**Issue by cor** [screeninteraction/jekyll-multiple-languages-plugin#59]

**Comment by Anthony-Gaudino** [comment]
No, for security reasons, currently GitHub pages doesn't allow you to use plugins.
Only a few official Jekyll plugins are supported.

Please see: https://help.github.com/articles/adding-jekyll-plugins-to-a-github-pages-site/

**Comment by cor** [comment]
Thanks for the info @Anthony-Gaudino, guess i'm out of luck then.
